# Generated by Django 5.0 on 2025-04-27 21:13

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('running', 'Running'), ('walking', 'Walking'), ('cycling', 'Cycling'), ('hiking', 'Hiking'), ('bodyweight', 'Bodyweight Training'), ('hiit', 'HIIT Workout'), ('yoga', 'Yoga/Stretching')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='powerup/workout_types/thumbnails/')),
                ('animation', models.FileField(blank=True, null=True, upload_to='powerup/workout_types/animations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(null=True, upload_to=api.models.user_folder, verbose_name='Image')),
                ('filename', models.CharField(max_length=255, null=True, verbose_name='Filename')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
