# Generated by Django 5.0 on 2025-04-27 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(default=0, help_text='Duration in minutes')),
                ('calories_burned', models.FloatField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userimagefile', verbose_name='User selfie image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
                ('workout_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workouttype', verbose_name='Workout Type')),
            ],
        ),
    ]
