# Generated by Django 5.0 on 2025-04-27 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_workout_user_alter_workout_img_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='api.profile'),
        ),
    ]
