# Generated by Django 5.0 on 2025-04-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Challenge Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Challenge Description')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='api.community')),
                ('workout_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='api.workouttype', verbose_name='Workout Type')),
            ],
        ),
    ]
