# Generated by Django 5.0 on 2025-04-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_community_admins_remove_community_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_communities', to='api.profile', verbose_name='Community Admins'),
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='communities', to='api.profile', verbose_name='Community Members'),
        ),
    ]
