# Generated by Django 5.0 on 2025-04-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_community_admins_community_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='points',
            field=models.FloatField(blank=True, default=0, verbose_name='Points Earned'),
        ),
        migrations.AddField(
            model_name='workouttype',
            name='calories_burn_rate',
            field=models.FloatField(blank=True, default=6, verbose_name='Calories Burn Rate Per Minute'),
        ),
        migrations.AddField(
            model_name='workouttype',
            name='points_rate',
            field=models.FloatField(blank=True, default=5, verbose_name='Points Earned Per Minute'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='calories_burned',
            field=models.FloatField(blank=True, default=0, verbose_name='Calories Burned'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.FloatField(default=0, help_text='Duration in Secondes', verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Workout Description'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='name',
            field=models.CharField(choices=[('running', 'Running'), ('walking', 'Walking'), ('cycling', 'Cycling'), ('hiking', 'Hiking'), ('bodyweight', 'Bodyweight Training'), ('hiit', 'HIIT Workout'), ('yoga', 'Yoga/Stretching')], max_length=50, unique=True, verbose_name='Workout Type Name'),
        ),
    ]
