# Generated by Django 5.0 on 2025-04-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_workout_points_workouttype_calories_burn_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouttype',
            old_name='calories_burn_rate',
            new_name='calories_burned_per_minute',
        ),
        migrations.RenameField(
            model_name='workouttype',
            old_name='points_rate',
            new_name='points_per_minutes',
        ),
    ]
