# Generated by Django 5.0 on 2025-04-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_calories_burn_rate_workouttype_calories_burned_per_minute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouttype',
            old_name='points_per_minutes',
            new_name='points_per_minute',
        ),
    ]
