# Generated by Django 5.0 on 2025-04-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_points_per_minutes_workouttype_points_per_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='api.workouttype', verbose_name='Workout Type'),
        ),
    ]
