# Generated by Django 5.0 on 2025-04-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_workout_workout_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='workouttype',
            options={'ordering': ['-id']},
        ),
    ]
