# Generated by Django 5.0 on 2025-04-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_challenge_options_alter_community_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='updated_at',
        ),
    ]
