# Generated by Django 5.0 on 2025-04-29 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_profile_height_alter_profile_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id']},
        ),
    ]
