# Generated by Django 5.0 on 2025-04-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_workout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='created_at',
        ),
    ]
