# Generated by Django 5.0 on 2025-05-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_workout_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeparticipant',
            name='progress',
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='points',
            field=models.FloatField(default=0, verbose_name='Points Earned'),
        ),
    ]
