# Generated by Django 5.0 on 2025-05-05 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_challengeparticipant_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeparticipant',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Joined'),
        ),
    ]
