# Generated by Django 5.0 on 2025-05-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_challengeparticipant_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeparticipant',
            name='joined_at',
        ),
    ]
