# Generated by Django 5.0 on 2025-05-06 00:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_challengeparticipant_joined_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='community',
            name='created_at',
        ),
        migrations.AddField(
            model_name='challenge',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='community',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
    ]
