# Generated by Django 5.0 on 2025-05-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_challenge_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='join_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
