# Generated by Django 5.0 on 2025-05-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_community_join_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='workout_type',
        ),
    ]
