# Generated by Django 5.0 on 2025-05-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_challenge_workout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='workout_types',
            field=models.ManyToManyField(blank=True, related_name='challenges', to='api.workouttype', verbose_name='Workout Types'),
        ),
    ]
