# Generated by Django 5.0 on 2025-05-08 05:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_challenge_workout_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovedCommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_community_member', to='api.community')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_community_member', to='api.profile')),
            ],
        ),
    ]
