# Generated by Django 5.0 on 2025-09-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_removedcommunitymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Workout Type Name'),
        ),
    ]
